# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1e4beba58cfca006cd64ce43843f2943b21643f9c69e4ead05c483289a7e52cdd7485de7a5ebe6c5c2afdbdff655975e7a1109a075c64832cd85ac5a818ee30a
  db_user: <%= ENV["DB_USER"] %>
  db_pass: <%= ENV["DB_PASS"] %>

test:
  secret_key_base: 230d261dbe072a479fd241d3bd7a8a622bc28b7aa74ffa2efed761dd33d44482a388c36d99c4d472bdbffba6e55e3bf495b2077fa82a7510000a0430c107afbb
  db_user: <%= ENV["DB_USER"] %>
  db_pass: <%= ENV["DB_PASS"] %>

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  db_user: <%= ENV["DB_USER"] %>
  db_pass: <%= ENV["DB_PASS"] %>
